# 输入数据
# 下面这些文件都放在input_data目录下
# 聊天记录
msg_file: msg.csv
# 微信表情中英文对照表
emoji_file: emoji.txt
# 停用词表，一般是没有实际意义的词，不想让被分析到的词都放在这里
stopword_file: stopwords_hit_modified.txt
# 词语转换表，用于合并意义相近的词，比如把“看到”、“看见”、“看看”都转换为“看”
transform_file: transformDict.txt
# 用户自定义词典，用于添加大部分字典没有的、但自己觉得不能分开的词，如i人、e人、腾讯会议
user_dict_file: userDict.txt

# 名字
# name1是自己的名字
name1: person 1
# name2是对方的名字
name2: person 2
# name_both是双方共同的名字
name_both: both

# 处理多少行，用于初期调试代码。可以是整数，也可以是'all'（全部处理）。
process_rows: 'all'

# 局部参数
# top_k是绘制前多少个词
# 如果词或表情的出现频次低于word_min_count或emoji_min_count，就不会被分析
# figsize是绘图图窗尺寸，第一个是宽度，第二个是高度
word_specificity:
  top_k: 25
  word_min_count: 2
  figsize:
  - 10
  - 12

emoji_specificity:
  emoji_min_count: 1
  top_k: 2
  figsize:
  - 10
  - 12

word_commonality:
  top_k: 25
  figsize:
  - 10
  - 12
  
emoji_commonality:
  top_k: 2
  figsize:
  - 12
  - 12

time_analysis:
  figsize:
  - 12
  - 8