# input_data
# 下面这些文件都放在input_data目录下
msg_file: msg.csv
emoji_file: emoji.txt
stopword_file: stopwords_hit_modified.txt
transform_file: transformDict.txt
user_dict_file: userDict.txt

# name
# name_both是双方共同的名字，name1是自己的名字，name2是对方的名字
name1: person 1
name2: person 2
name_both: both

# 局部参数
word_specificity:
  top_k: 25
  word_min_count: 2
  figsize:
  - 10  # width
  - 12  # height

emoji_specificity:
  emoji_min_count: 1
  top_k: 5
  figsize:
  - 10
  - 12

word_commonality:
  top_k: 25
  figsize:
  - 10
  - 12
  
emoji_commonality:
  top_k: 5
  figsize:
  - 12
  - 12

time_analysis:
  figsize:
  - 12
  - 8